P3-StephenRhoades:  P3-sem-StephenRhoades.o mytime.o
	gcc -Wall -std=c99 -lpthread -o P3-sem-StephenRhoades P3-sem-StephenRhoades.o mytime.o
P3-StephenRhoades.o: P3-StephenRhoades.c mytime.h
	gcc -c P3-sem-StephenRhoades.c -lpthread -Wall -std=c99
mytime.o: mytime.c
	gcc -c mytime.c -Wall -std=c99
