P4-YourFirstLastName:  P4-YourFirstLastName.o mytime.o
	gcc -Wall -std=c99 -lpthread -o P4-YourFirstLastName P4-YourFirstLastName.o mytime.o
P4-YourFirstLastName.o: P4-YourFirstLastName.c mytime.h
	gcc -c P4-YourFirstLastName.c -lpthread -Wall -std=c99
mytime.o: mytime.c
	gcc -c mytime.c -Wall -std=c99
